services:
  db:
    container_name: db_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  api:
    container_name: api
    image: "alexandrudaniel/my-spring-app:latest"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    depends_on:
      - db


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
