services:
  db_container:
    container_name: db_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
    volumes:
      - /init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - db_container
    restart: unless-stopped

  api:
    container_name: api
    image: "alexandrudaniel/my-spring-app:latest"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    networks:
      - db_container
    depends_on:
      - db_container


networks:
  db_container:
    driver: bridge

