apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pod
  labels:
    app: api-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-pod
  template:
    metadata:
      name: api-pod
      labels:
        app: api-pod
    spec:
      containers:
        - name: api-pod
          image: alexandrudaniel/my-spring-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
#          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: k8s

