apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
